name: Newstide
description: "News application for Final exams"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^8.1.3
  go_router: ^14.0.1
  get_it: ^7.6.0
  shared_preferences: ^2.5.3
  iconsax_plus: ^1.0.0
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/N.jpg"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
